# -------- text --------
[[previewer]]
mime = "text/*"
run = "hx -p \"$1\""

# -------- structured text --------
[[previewer]]
mime = "application/json"
run = "hx -v \"$1\""

[[previewer]]
mime = "application/toml"
run = "hx -v \"$1\""

[[previewer]]
mime = "application/yaml"
run = "hx -v \"$1\""

[[previewer]]
mime = "application/xml"
run = "hx -v \"$1\""

# -------- markdown --------
[[previewer]]
mime = "text/markdown"
run = "glow -s dark \"$1\""

# -------- image --------
[[previewer]]
mime = "image/*"
run = "yazi-preview \"$1\""

# pdf
[[previewer]]
mime = "application/pdf"
run = "yazi-preview \"$1\""

# video
[[previewer]]
mime = "video/*"
run = "yazi-preview \"$1\""

# archive
[[previewer]]
mime = "application/*"
run = "7z l \"$1\""