[manager]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
theme = "tokyo-night"

[opener]
hx = [
  { run = "hx \"$@\"", desc = "Open in hx" }
]

[open]
prepend_rules = [
  { mime = "text/*", use = "hx" },
  { mime = "application/json", use = "hx" },
  { mime = "application/toml", use = "hx" },
  { mime = "application/yaml", use = "hx" },
  { mime = "application/xml", use = "hx" },
]
