#https://docs.helix-editor.com/editor.html
theme = "noctis"

[editor]
line-number = "relative"   # 相对行号 (Vim/Helix 神器，方便 jump)
cursorline = true          # 高亮当前行
bufferline = "always"      # 始终显示顶部 Buffer 列表，看起来就像 IDE 的 Tab
auto-format = true
auto-save = false
idle-timeout = 400         # 让快捷键提示菜单弹出时间
completion-timeout = 5
completion-trigger-len = 1 # 代码补全更积极
true-color = true          # 真彩色支持
scroll-lines = 3
color-modes = true         # 模式变色 (Insert红/Normal蓝)
mouse = true               # 允许鼠标点击/滚动

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
# 文件
space.w = ":w"
space.q = ":q"
space.x = ":wq"
space.e = ":open ~/.config/helix/config.toml"

# 搜索 / 跳转
space.f = "file_picker"
space.F = "file_picker_in_current_directory"
space.b = "buffer_picker"
space.s = "global_search"

# 诊断
space.d = "diagnostics_picker"