# Rust
[language-server.rust-analyzer]
command = "rust-analyzer"

# C/C++ (clangd)
[language-server.clangd]
command = "clangd"

# Python (pyright)
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

# Java (jdt.ls)
[language-server.eclipse-jdt-ls]
command = "jdtls"

# Go (gopls)
[language-server.gopls]
command = "gopls"

# TypeScript / JavaScript
[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
