# -------- text --------
[[previewer]]
mime = "text/*"
run = "hx -p \"$1\""

# -------- structured text --------
[[previewer]]
mime = "application/json"
run = "bat --color=always --style=plain --paging=never \"$1\""

[[previewer]]
mime = "application/toml"
run = "hx -v \"$1\""

[[previewer]]
mime = "application/yaml"
run = "hx -v \"$1\""

[[previewer]]
mime = "application/xml"
run = "hx -v \"$1\""

# -------- markdown --------
[[previewer]]
mime = "text/markdown"
run = "glow -s dark \"$1\""

# -------- image --------
[[previewer]]
mime = "image/*"
run = "chafa \"$1\""

# -------- pdf --------
[[previewer]]
mime = "application/pdf"
run = "pdftoppm -singlefile -jpeg \"$1\" - | chafa"

# -------- video--------
[[previewer]]
mime = "video/*"
run = "ffmpegthumbnailer -i \"$1\" -o - -s 0 | chafa"

# archive
[[previewer]]
mime = "application/*"
run = "7z l \"$1\""